cargo-features = ["edition"]

[package]
edition = "2018"
name = "client"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[dependencies]
bincode = "1.0.1"
brotli = "2.5.0"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
stdweb = "0.4.8"
yew = "0.4.0"
