cargo-features = ["edition"]

[package]
edition = "2018"
name = "client"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
brotli = "2.5.0"
#js-sys = "0.2.0"
wasm-bindgen = "0.2.15"
#web-sys = "0.0.1"
