[package]
edition = "2018"
name = "scroadmap"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[workspace]
members = [
    "client",
    "converter",
    "fetcher",
    "util",
]

[dependencies]
bincode = "1.0.1"
brotli = "3.1.5"
serde = "1.0.82"
serde_derive = "1.0.82"
