[package]
name = "fetcher"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.10"
scroadmap = { path = "../" }
serde_json = "1.0.39"
util = { path = "../util" }