[package]
edition = "2018"
name = "service"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[dependencies]
actix-web = { version = "0.7.8", default-features = false }
scroadmap = { path = "../" }
reqwest = "0.9.2"
serde_json = "1.0.31"
