[package]
name = "converter"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]
edition = "2018"

[dependencies]
scroadmap = { path = "../" }
serde_json = "1.0.37"
util = { path = "../util" }